### ISSUE TITLE
[1.18.2] Mods missed as clientside on the dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#22] opened 2022-09-02 03:57 UTC
**Describe the bug**
The mods in the screenshot listed as .clientside are mods missed when flagging mods for server side.

**To Reproduce**
Install TownCraft 1.18.2 and run it on a dedicated server.

**Screenshots**
![image](https://user-images.githubusercontent.com/4427684/188056009-a5c3a5cb-613e-46bf-a152-e5de6e483f92.png)

**Comment by MarkusBordihn** [comment] 2022-09-02 10:29
Could you please explain the "expected behavior" and "why" this is causing an issue in your case ?

The mod module is expected to disable all pure client side mods on the server, because there are not needed on the server side at all.
See: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/tree/main/mods

If a missing client side mod displayed the server as incompatible, this should not prevent you to login and needs to be fixed by the client side mod owner like:
https://github.com/mezz/ItemZoom/pull/33

If you don't want this feature, you could just remove the [adaptive_performance_tweaks_mods_???.jar](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-mods) mod file, which is not part of the standard bundle and needs to be added manually.

**Comment by ProsperCraft** [comment] 2022-09-02 12:52
Expected behavior- all clientside only mods that are not needed on the server are flagged as client effectively disabling them on the server side.

Current behavior-  Not all clientside mods are flagged and renamed causing clients not being able to log in unless they manually disable them.

**Comment by MarkusBordihn** [comment] 2022-09-02 16:29
Thanks for the feedback, but I'm still missing some needed details to fully understand the issue here.

**Not all clientside mods are flagged ...**

Unfortunately this is expected, because it's not possible to fully automate this.
There is no way to 100% detect automatically, if an mod is client side only or is needed on the server side.
For this reason I need to maintain semi-automatically a list with tested mods like:
https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/blob/1.18.2/mods/src/main/java/de/markusbordihn/minecraft/adaptiveperformancetweaksmods/config/ModsDatabase.java

I currently working on a config file, which could be adjusted by users for the different needs, so that it is no longer a hardcoded list.

**Renamed causing clients not being able to log in unless they manually disable them**

This is something which should not happen at all. If a mod is really client side only you should be still able to connect to the server even if you seeing a "red cross" for the server.
If this is not the case make sure that you don't use any mods which adjust these kinds of checks for server compability.

You should also report the issue to the client side mod owner to fix the issue or to get the confirmation if the mod is really 100% client side only.

I'm happy to check this more in detail, but for this I would need a client side log which refused to connect to the server to see why the client side mod was rejected.

**Comment by MarkusBordihn** [comment] 2022-09-03 12:01
I updated the client side mod list with some additional mods and you are now able to maintain your own customize list.
There are some mods in your screenshot which are not pure client side mods and include an optional server feature, but most of the other should be covered with this update.

As I mentioned for the other issue **Renamed causing clients not being able to log in unless they manually disable them** is something which you should check with the client side mod owner more in detail. If there is an wrongly added client side mode in my current list, let me know and I will double check it.

Fixed with: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/commit/8b294ee63d90db9c44e0d8a73e5b521f05925b36

**Closed by MarkusBordihn** 2022-09-03 12:01 UTC
Labels: invalid
